export const productosIniciales =[
    {
        id: '1',
        nombre: "Arlyt",
        precio: 1130,
        imagen: "/arlytExpress120.jpg",
        descripcion:"ARLYT EXPRESS MULTIUSO SOLUCIÓN MULTIPROPÓSITO E ISOTÓNICA PARA TODO TIPO DE LENTES DE CONTACTO BLANDAS. LIMPIADORA, DESINFECTANTE, CONSERVADORA, HUMECTANTE Y DE ENJUAGUE.",
        categoria: '1',
    },
    {
        id: '2',
        nombre: "Natura Express",
        precio: 1200,
        imagen: "/naturaExpess.jpg",
        descripcion:"NATURA EXPRESS MULTIUSO SOLUCIÓN MULTIPROPÓSITO E ISOTÓNICA PARA TODO TIPO DE LENTES DE CONTACTO BLANDAS. LIMPIADORA, DESINFECTANTE, CONSERVADORA, HUMECTANTE Y DE ENJUAGUE.",
        categoria: '2',
    },
    {
        id: '3',
        nombre: "Renu",
        precio: 1290,
        imagen: "/renuchico.jpg",
        descripcion:"RENU PLUS MULTIUSO SOLUCIÓN MULTIPROPÓSITO E ISOTÓNICA PARA TODO TIPO DE LENTES DE CONTACTO BLANDAS. LIMPIADORA, DESINFECTANTE, CONSERVADORA, HUMECTANTE Y DE ENJUAGUE.",
        categoria: '3',
    }
    //{
     //   id: '4',
       // nombre: "Boston Simplus",
        //precio: 1290,
        //imagen: "/bostonSimplus.jpg",
        //descripcion:"El liquido multiuso Boston Simplus de Bausch & Lomb es ideal para usuarios de lentes de contacto rígidas gas permeables que buscan practicidad.",
        //categoria: '3', 
    //},
    //{
      //  id: '5',
        //nombre: "Renu Gotas",
        //precio: 598,
        //imagen: "/renuGotas.jpg",
        //descripcion:"Las gotas lubricantes Renu Plus Drops 8ml del laboratorio Bausch & Lomb para el cuidado de las lentes de contacto blandas de hidrogel e hidrogel de silicona. Limpia, enjuaga, desinfecta, lubrica y remueve proteínas. Solución isotónica estéril fórmula que contiene: ácido bórico, edetato de sodio, borato de sodio, cloruro de sodio.",
        //categoria: '3',
    //},
    //{
       // id: '6',
        //nombre: "Natura Plus",
        //precio: 920,
        //imagen: "/naturaPlus.jpg",
        //descripcion:"Para Limpieza Diaria, Remoción De Proteínas, Lubricación, Enjuague Y Conservación De Lentes De Contacto Blandas. Desinfección Química De Lentes De Contacto Blandas. Inhibe La Formación De Depósitos. Limpia, Humecta, Desinfecta, Conserva, Enjuaga. Remueve Los Depósitos De Proteínas Y Lípidos.",
        //categoria: '2',
    //},
    //{
      //  id: '7',
        //nombre: "Arlyt Lubricante",
        //precio: 516,
        //imagen: "/arlytLubricante.jpg",
        //descripcion:"Solución para la lubricación de los ojos y las lentes.Lubrica la superficie de la lente y mantiene la hidratación durante las horas de uso.Contiene Hialuronato de Sodio, aumentado el confort en el uso de las lentes.",
        //categoria: '1',
    //},
    //{
      //  id: '8',
        //nombre: "Arlyt Premium",
        //precio: 1570,
        //imagen: "/arlytPremium.jpg",
        //descripcion:"Arlyt Premium con Hialuronato de Sodio: Solución estéril e isotónica multiuso para lentes blandas de hidrogel y de hidrogel de silicona. Limpiadora, desinfectante, conservadora, humectante, lubricante y de enjuague. Alta capacidad de Hidratación de efecto prolongado.",
        //categoria: '1',
    //}
];